# Site settings
title: TamilMithraa
owner_name: TamilMithran
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A wholesome package of Poetry and Literature.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tamil.mithraa.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

#kramdown settings
kramdown:
  parse_block_html: true

#permalink settings
permalink: pretty

#gems
gems:

# jekyll-sitemap
  - jekyll-sitemap

#google analytics tracking code
ga_tracking: "UA-70675514-2"
